config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
 	
 	# Authentication
 	# @implemented
  devise_for :users, :controllers => {
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Application
  # @implemented
  root to: 'home#index'
  resources :groups

  # Dashboard
  # @implemented
  namespace :dashboard do
  	get '/', to: 'home#index'
  	resources :profiles
  	resources :accounts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# frozen_string_literal: true
class Group < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: :slugged
	
	self.table_name = 'groups'
	self.primary_key = 'id'

	validates :name,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 70 }

	validates :email,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 245 }

	validates :website,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 245 }

	validates :address,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 145 }

	validates :region,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 2, maximum: 145 }

  validates :country,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 145 }
end

app/models/profile.rb
# frozen_string_literal: true	
class Profile < ApplicationRecord
  self.table_name = 'profiles'
  self.primary_key = 'id'

  belongs_to :user, optional: false
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
	extend FriendlyId
	friendly_id :nickname, use: :slugged

	self.table_name = 'users'
	self.primary_key = 'id'
  
  has_one :profile, dependent: :destroy
  after_create :create_profile
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]

  def create_profile
  	build_profile.save
  end

  def self.new_with_session	(params, session)
  	super.tap do |user|
    	if data = session["devise.facebook_data"] && 
    	 session["devise.facebook_data"]["extra"]["raw_info"]
     	 user.email = data["email"] if user.email.blank?
    	end
  	end
	end

	def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
   	 user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
	   user.name = auth.info.name   # assuming the user model has a name
	   user.avatar = auth.info.image # assuming the user model has an image
  	end
	end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  # before_filter :configure_permitted_parameters, if: :devise_controller?

  self.responder = ApplicationResponder
  respond_to :html

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :username, :email, :password, :password_confirmation)}
  end
end

app/controllers/dashboard/home_controller.rb
# frozen_string_literal: true
module Dashboard
	class HomeController < ApplicationController
	  before_action :authenticate_user!

	  def index
	  	# some code here
	  end
	end
end

app/controllers/dashboard/profiles_controller.rb
# frozen_string_literal: true
module Dashboard
	class ProfilesController < HomeController
	  before_action :set_profile, only: [:show, :edit, :update, :destroy]

	  def index
	  	@profile = current_user.profile
	  	render 'index'
	  end

	  def show
	  	respond_with(@profile)
	  end

	  def edit
	  	respond_with(@profile)
	  end

  	def update
    	@profile.update(profile_params)
    	respond_with(:dashboard, @profile)
  	end

  	def destroy
    	@profile.user.destroy
    	redirect_to destroy_user_session_path, method: :delete
  	end

	  private

	  def set_profile
	  	@profile = Profile.find(params[:id])
	  end

	  def profile_params
	  	params.require(:profile)
	  		.permit(:birthdate, :gender, :bio, :location, :state, :country)
	  end
	end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :js

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :email, :website, :address, :region, :country)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/home_helper.rb
module Dashboard
	module HomeHelper

	end
end

app/helpers/dashboard/profile_helper.rb
module Dashboard::ProfileHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/home/index.html.erb
<h1>Dashboard::Home#index</h1>
<p>Find me in app/views/dashboard/home/index.html.erb</p>

app/views/dashboard/profiles/_form.html.erb
<%= form_with(model: [:dashboard, profile], local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :birthdate, 'Data de Nascimento' %> <span class='required'>*</span>
    <%= form.date_field :birthdate, class: 'form-control', required: 'required',
    placeholder: 'Digite a data de nascimento', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :gender, 'Genero' %> <span class='required'>*</span>
    <%= form.select(:gender, {'Masculino' => 'Masculino', 'Feminino' => 'Feminino'},
    {prompt: 'Selecionar o Genero'}, {class: 'form-control', required: 'required'}) %>
  </div>

  <div class="field">
    <%= form.label :bio, 'Biografia' %> <span class='required'>*</span>
    <%= form.text_area :bio, class: 'form-control', required: 'required',
    placeholder: 'Conte-nos um pouco sobre você', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :location, 'Localização' %> <span class='required'>*</span>
    <%= form.text_field :location, class: 'form-control', required: 'required',
    placeholder: 'Digite seu endereço / cidade', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :state, 'Estado' %> <span class='required'>*</span>
    <%= form.text_field :state, class: 'form-control', required: 'required',
    placeholder: 'Digite o estado', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :country, 'Pais' %> <span class='required'>*</span>
    <%= form.text_field :country, class: 'form-control', required: 'required',
    placeholder: 'Digite o país', autocomplete: 'off' %>
  </div>

  <div class="actions"><br>
    <%= form.submit nil, class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/dashboard/profiles/edit.html.erb
<section id='group'>
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
			 <h1>Editing Profile</h1>
			 <%= render 'form', profile: @profile %>

			 <%= link_to 'Show', [:dashboard, @profile] %> |
			 <%= link_to 'Back', dashboard_profile_path %>
			</div>
		</div>
	</div>
</section>

app/views/dashboard/profiles/index.html.erb
<% provide :title, 'Dashboard' %>

<section id="presenter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Bem vindo <%= link_to current_user.name %></h2>
				<p>Fique avontade para explorar as comunidades rubistas as redor do mundo.</p>
				<ul class='list-inline'>
					<li><%= button_to 'Meu Perfil', edit_dashboard_profile_path(current_user.profile.id),
					method: :get, class: 'btn btn-primary btn-lg', style: 'margin-left: 0px;' %> </li>
			  	<li><%= button_to 'Deletar Perfil', dashboard_profile_path(current_user.profile.id),
					method: :delete, class: 'btn btn-danger btn-lg', style: 'margin-left: 0px;',
					data: { confirm: 'Are you sure?' } %> </li>
			</div>
		</div>
	</div>
</section>

app/views/dashboard/profiles/show.html.erb
<% provide :title, @profile.user.name %>

<section id="profile">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Data de nascimento:</strong>
          <%= @profile.birthdate %>
        </p>

        <p>
          <strong>Genero:</strong>
          <%= @profile.gender %>
        </p>

        <p>
          <strong>Bio:</strong>
          <%= @profile.bio %>
        </p>

        <p>
          <strong>Localização:</strong>
          <%= @profile.location %>
        </p>

        <p>
          <strong>Estado:</strong>
          <%= @profile.state %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @profile.country %>
        </p>

        <%= link_to 'Edit', edit_dashboard_profile_path(@profile) %> |
        <%= link_to 'Back', dashboard_profile_path %>
      </div>
    </div>
  </div>
</section>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <span class='required'>*</span>
    <%= form.text_field :name, class: 'form-control', required: 'required',
    placeholder: 'Digite o nome', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :email %> <span class='required'>*</span>
    <%= form.text_field :email, class: 'form-control', required: 'required',
    placeholder: 'Digite o e-mail', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :website %> <span class='required'>*</span>
    <%= form.text_field :website, class: 'form-control', required: 'required',
    placeholder: 'Digite o website', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :address %> <span class='required'>*</span>
    <%= form.text_field :address, class: 'form-control', required: 'required',
    placeholder: 'Digite o endereço', autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= form.label :region %> <span class='required'>*</span>
    <%= form.text_field :region, class: 'form-control', required: 'required',
    placeholder: 'Digite a região', autocomplete: 'off' %>
  </div>

  <div class="field"> 
    <%= form.label :country %> <span class='required'>*</span>
    <%= form.text_field :country, class: 'form-control', required: 'required',
    placeholder: 'Digite o país', autocomplete: 'off' %>
  </div>

  <div class="actions"><br>
    <%= form.submit nil, class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<section id='group'>
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
			 <h1>Editing Group</h1>
			 <%= render 'form', group: @group %>

			 <%= link_to 'Show', @group %> |
			 <%= link_to 'Back', groups_path %>
			</div>
		</div>
	</div>
</section>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Website</th>
      <th>Address</th>
      <th>Region</th>
      <th>Contry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.email %></td>
        <td><%= group.website %></td>
        <td><%= group.address %></td>
        <td><%= group.region %></td>
        <td><%= group.country %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<% provide :title, 'Adicionar' %>

<section id='group'>
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
				<h1>New Group</h1>
				<%= render 'form', group: @group %>

				<%= link_to 'Back', groups_path %>
			</div>
		</div>
	</div>
</section>

app/views/groups/show.html.erb
<% provide :title, @group.name %>

<section id="group">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @group.name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @group.email %>
        </p>

        <p>
          <strong>Website:</strong>
          <%= @group.website %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= @group.address %>
        </p>

        <p>
          <strong>Region:</strong>
          <%= @group.region %>
        </p>

        <p>
          <strong>Contry:</strong>
          <%= @group.country %>
        </p>

        <%= link_to 'Edit', edit_group_path(@group) %> |
        <%= link_to 'Back', groups_path %>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<% provide :title, 'Home' %>

<section id='presenter' class="jumbotron">
	<div class='container'>
		<div class='col-md-12'>
			<div class='row'>
				<div class='col-md-6 col-md-offset-3'>
				<%= form_for :group do |f| %>
					<div class='field col-md-9'>
						<div class='input-group'>
							<div class='input-group-addon'><i class="fas fa-map-marker-alt"></i></div>
						<%= f.search_field :name, class: 'form-control', required: 'required',
						placeholder: 'Nome, Estado, Cidade ou Região', autocomplete: 'off' %>
						  <div class='input-group-addon'><i class="fas fa-map-marker-alt"></i></div>
						</div>
					</div>
					<div class="field col-md-2">
						<%= f.submit 'Buscar', class: 'btn btn-primary btn-lg top' %>
					</div>
				<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

<br>
<section id="groups">
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
				<% Group.all.each do |group| %>
				 <% for i in 1..6 %>
					<div class="col-md-3">
						<div class="jumbotron" style='margin-bottom: 0px; border-radius: 0px; height: 140px;'></div>
						<div class='panel panel-default' style='padding: 20px;'>
							<h4><%= link_to group.name, group_path(group) %></h4>
							<small>
								<%= group.address %>  /
								<%= group.region  %>  /
								<%= link_to group.country, groups_path(country: group.country.downcase) %> 
							</small>
						</div>
					</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<footer class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Rubyster</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%= link_to 'Inicio',  root_path %></li>
      	<li><%= link_to 'Sobre',   root_path %></li>
      	<li><%= link_to 'Contato', root_path %></li>
      </ul>
			
			<%= form_for :group, {html: {class: 'navbar-form navbar-left', id: 'headerSearch'}} do |f| %>
				<div class='form-group'>
					<div class='input-group'>
						<div class='input-group-addon'><i class="fas fa-map-marker-alt"></i></div>					
						<%= f.search_field :name, class: 'form-control', required: 'required',
						placeholder: 'Nome, Estado, Cidade ou Região', autocomplete: 'off' %>
						</div>
				</div>
				<%= f.submit 'Buscar', class: 'btn btn-primary top' %>
			<% end %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= button_to 'Adicionar Grupo', new_group_path, method: :get, 
        class: 'btn btn-primary btn-sm', style: 'margin-top: 7px; padding: 8px;' %></li>
        <% if current_user %>
					<% if current_user.avatar.present? %>
        	<li><%= image_tag(current_user.avatar, class: 'header-avatar', style: 'width: 44px; height: 44px; border-radius: 44px; margin-top: 3px; margin-left: 10px;') %></li>
        	<% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Dashboard', dashboard_path %></li>
            <li><%= link_to 'Perfil', dashboard_profiles_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sair', destroy_user_session_path,  :method=> :delete %></li>
          </ul>
        </li>
        <% else %>
				 <li><%= button_to 'Criar conta', new_user_registration_path, method: :get, class: 'btn btn-danger btn-sm', style: 'margin-top: 7px; margin-left: 10px; padding: 8px;' %></li>
         <li><%= link_to 'Entrar', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Rubyster - <%= yield :title %></title>
    <meta charset=utf-8>
    <meta name=description content="">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type='text/css'><%= yield :css %></style>
    <script type='text/javascript'><%= yield :js %></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= alertify_flash(wait: 7) %>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>